spring.application.name=Inventarios

# 1. URL de conexión para PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_db

# 2. Tus credenciales locales
spring.datasource.username=postgres
spring.datasource.password=1965

# 3. El Driver oficial para que Java sepa cómo hablar con Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Configuración de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect